### ISSUE TITLE
Error: Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by the-red** [goqoo-on-kintone/ginue#1]
グローバルインストールして非npmプロジェクトで使おうとするとこんなエラーになった。
依存関係の解決など要調査。
npm, yarnどちらでインストールしても同じ。

```
Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/current/node_modules/ginue/index.js:5:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by the-red** [comment]
```
yarn add global mkdirp
```
で入れてやれば動くようにはなった。
でもこの状況は好ましくない。package.json修正すべき。

**Comment by the-red** [comment]
1.0.2で修正完了
https://github.com/TailsGarden/ginue/commit/98414b000e7f3f8e115951d08c5c77a326c4a254
